#!/bin/bash
# Script aby sprawdzić i naprawić Supabase Auth settings

echo "=== Supabase Auth Fix - High Bounce Rate ==="
echo ""
echo "Problem: Supabase blokuje wysyłanie emaili z powodu wysokiego bounce rate"
echo "Rozwiązanie: Wyłącz email confirmation dla development"
echo ""
echo "Kroki do wykonania:"
echo ""
echo "1. Przejdź do Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/odeyguqwoqypctwzlajm/auth/users"
echo ""
echo "2. Kliknij 'Configuration' lub 'Settings' → 'Authentication'"
echo ""
echo "3. W sekcji 'Email Auth' znajdź:"
echo "   ✅ 'Enable email confirmations' - WYŁĄCZ dla development"
echo "   ✅ 'Secure email change' - możesz też wyłączyć dla development"
echo ""
echo "4. Zapisz zmiany"
echo ""
echo "5. Opcjonalnie: Potwierdź istniejących użytkowników SQL:"
echo "   UPDATE auth.users SET email_confirmed_at = now() WHERE email_confirmed_at IS NULL;"
echo ""
echo "=== Dla Produkcji ==="
echo ""
echo "Skonfiguruj custom SMTP provider:"
echo "1. Dashboard → Project Settings → Auth"
echo "2. SMTP Settings → Enable custom SMTP"
echo "3. Użyj np. SendGrid, Mailgun, AWS SES"
echo ""
echo "Więcej info: https://supabase.com/docs/guides/auth/auth-smtp"
echo ""

